### ISSUE TITLE
Maybe you can also add the `!`? Right now we have to manually edit the file to add that in after transforming

### ISSUE THREAD

**Issue by antongolub** [antongolub/tsc-esm-fix#90]
thx. Maybe you can also add the `!`? Right now we have to manually edit the file to add that in after transforming

_Originally posted by @unional in https://github.com/antongolub/tsc-esm-fix/issues/89#issuecomment-1214433826_

**Comment by antongolub** [comment]
@unional, `2.20.2`, your turn.

**Comment by unional** [comment]
`(/file:\/{2,3}(.+)\/[^/]/.exec(import.meta.url) || [])[1]` that gives me butterflies... :)

It it true that `([])[1]` gives `undefined`, but it's not a good practice.

Yes, while this is more defensive than using `!`, but IMO that mask the actual problem (that in certain case the regex fails).

IMO, I would prefer using `!` to make sure it fail fast (getting an accessing `1` from `undefined` error) instead of discovering the error later on.

**Comment by antongolub** [comment]
`!` — agree, nice option for ts files, but ecma standard, IINM, did not introduce smth similar.

**Comment by antongolub** [comment]
I suggest to introduce alternative subs syntax:
`--dirnameVar = true / 'expression'` — current legacy impl
`--dirnameVar = 'const'` — append constants to the begining of files

**Comment by unional** [comment]
The `!` is TypeScript only syntax. Tt is removed after transpilation. It is just an assertion to tell TS to be quiet.

**Comment by antongolub** [comment]
I'm a little confused. tsc-esm-fix can be used for both sources and bundles. And the latter are no longer subject to change.

**Comment by unional** [comment]
I see. Then adding `!` is a no-go. Unless you can detect whether the source is TS or JS.

**Comment by antongolub** [comment]
Ah, now it's clear! I'll land this improvement tomorrow.

**Comment by antongolub** [comment]
Done. `2.20.3` is waiting for feedback

**Comment by unional** [comment]
Working as expected! 🎉
