### ISSUE TITLE
incorrectly adds .js to "react/jsx-runtime";

### ISSUE THREAD

**Issue by gajus** [antongolub/tsc-esm-fix#96]
```diff
-import { jsx as _jsx } from "react/jsx-runtime";
+import { jsx as _jsx } from "react/jsx-runtime.js";
```

Do not expect this transform

**Comment by antongolub** [comment]
@gajus,

It looks strange. By design all external modules which have `exports` field in their pkgjson _should be_ omitted from subs variants. Moreover, I have a test for this case:
* fixture: https://github.com/antongolub/tsc-esm-fix/blob/master/src/test/fixtures/ts-project/node_modules/e2/package.json#L10
* snapshot: https://github.com/antongolub/tsc-esm-fix/blob/master/src/test/ts/__snapshots__/fix.ts.snap#L27

Could you plz add more context for debug? Repo link that reproduces the issue would be perfect.

**Comment by PeterBenko** [comment]
I think I'm facing a similar issue - in my case with @playwright/test imports:
```diff
-import { test } from '@playwright/test';
+import { test } from '@playwright/test/index.js';
```
I suspected that this is due to playwright [exports being an object](https://github.com/microsoft/playwright/blob/9e91ca353c27cda89d16d2fff8ab270894866c0d/packages/playwright/package.json#L14-L19), which doesn't seem to be a tested case in the fixture that you linked. However, manually editing their local package.json doesn't change the behaviour

**Comment by antongolub** [comment]
I'll try to take a look next week.
